s502 assembler: /github/workspace/src/debugmalloc.h File Reference
debugmalloc.h File Reference
#include <stdbool.h>
#include <stddef.h>
#include <stdlib.h>
#include <stdio.h>
#include <ctype.h>
#include <string.h>
#include <stdarg.h>
#include <unistd.h>
Data Structures
struct DebugmallocElem
struct DebugmallocData
Macros
#define malloc(S) debugmalloc_malloc_full((S), "malloc", #S, __FILE__, __LINE__, false)
#define calloc(N, S) debugmalloc_malloc_full((N)*(S), "calloc", #N ", " #S, __FILE__, __LINE__, true)
#define realloc(P, S) debugmalloc_realloc_full((P), (S), "realloc", #S, __FILE__, __LINE__)
#define free(P) debugmalloc_free_full((P), "free", __FILE__, __LINE__)
Enumerations
enum {
debugmalloc_canary_size = 64, OPC_INVALID = 0xff, MAP_MAX_KEY_LEN = 32, NUMBER_ERROR = -1,
NUMBER_LABEL_NODEF = -2, STATE_MAX_STRING_LEN = 32, TOKEN_BUFFER_SIZE = 100, TOKEN_SOURCE_FILE_SIZE = 32
}
enum { debugmalloc_canary_char = 'K' }
enum { debugmalloc_tablesize = 256 }
Functions
static DebugmallocData * debugmalloc_create (void)
static DebugmallocData * debugmalloc_singleton (void)
static void debugmalloc_strlcpy (char *dest, char const *src, size_t destsize)
static void debugmalloc_log_file (char const *logfilename)
static void debugmalloc_log (char const *format,...)
static void debugmalloc_memory_init (DebugmallocElem *elem, bool zero)
static bool debugmalloc_canary_ok (DebugmallocElem const *elem)
static void debugmalloc_dump_memory (char const *mem, size_t size)
static void debugmalloc_dump_elem (DebugmallocElem const *elem)
static void debugmalloc_dump (void)
static void debugmalloc_atexit_dump (void)
static size_t debugmalloc_hash (void *address)
static void debugmalloc_insert (DebugmallocElem *entry)
static DebugmallocElem * debugmalloc_find (void *mem)
static int debugmalloc_allocated_count (void)
static void * debugmalloc_malloc_full (size_t size, char const *func, char const *expr, char const *file, unsigned line, bool zero)
static void debugmalloc_free_inner (DebugmallocElem *deleted)
static void debugmalloc_free_full (void *mem, char const *func, char const *file, unsigned line)
static void * debugmalloc_realloc_full (void *oldmem, size_t newsize, char const *func, char const *expr, char const *file, unsigned line)
Data Structure Documentation
DebugmallocElem
struct DebugmallocElem
Definition at line 51 of file debugmalloc.h.
Data Fields
char expr[128]
char file[64]
char func[32]
unsigned line
struct DebugmallocElem * next
struct DebugmallocElem * prev
void * real_mem
size_t size
void * user_mem
DebugmallocData
struct DebugmallocData
Definition at line 66 of file debugmalloc.h.
Data Fields
DebugmallocElem head[debugmalloc_tablesize]
char logfile[256]
DebugmallocElem tail[debugmalloc_tablesize]
Macro Definition Documentation
calloc
#define calloc (N, S) debugmalloc_malloc_full((N)*(S), "calloc", #N ", " #S, __FILE__, __LINE__, true)
Definition at line 479 of file debugmalloc.h.
free
#define free (P) debugmalloc_free_full((P), "free", __FILE__, __LINE__)
Definition at line 481 of file debugmalloc.h.
malloc
#define malloc (S) debugmalloc_malloc_full((S), "malloc", #S, __FILE__, __LINE__, false)
Definition at line 478 of file debugmalloc.h.
realloc
#define realloc (P, S) debugmalloc_realloc_full((P), (S), "realloc", #S, __FILE__, __LINE__)
Definition at line 480 of file debugmalloc.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
debugmalloc_canary_size
OPC_INVALID
An invalid opcode to signal invalid / non-existent variations.
MAP_MAX_KEY_LEN
Key buffer size for Map.
NUMBER_ERROR
Could not parse a number or constant is undefined.
NUMBER_LABEL_NODEF
Undefined label.
STATE_MAX_STRING_LEN
max string length for input/output files
TOKEN_BUFFER_SIZE
Token max length.
TOKEN_SOURCE_FILE_SIZE
source filename max length. Longer strings will get truncated.
Definition at line 41 of file debugmalloc.h.
 { debugmalloc_canary_size = 64 };
anonymous enum
anonymous enum
Enumerator
debugmalloc_canary_char
Definition at line 44 of file debugmalloc.h.
 { debugmalloc_canary_char = 'K' };
anonymous enum
anonymous enum
Enumerator
debugmalloc_tablesize
Definition at line 47 of file debugmalloc.h.
 { debugmalloc_tablesize = 256 };
Function Documentation
debugmalloc_allocated_count()
static int debugmalloc_allocated_count (void) static
Definition at line 305 of file debugmalloc.h.
{
     DebugmallocData *instance = debugmalloc_singleton();
     int count = 0;
     for (size_t i = 0; i < debugmalloc_tablesize; i++) {
         for (DebugmallocElem *iter = instance->head[i].next; iter != &instance->tail[i]; iter = iter->next)
             count += 1;
     }
     return count;
 }
References debugmalloc_singleton(), debugmalloc_tablesize, DebugmallocData::head, DebugmallocElem::next, and DebugmallocData::tail.
Referenced by debugmalloc_create().
debugmalloc_atexit_dump()
static void debugmalloc_atexit_dump (void) static
Definition at line 251 of file debugmalloc.h.
{
     DebugmallocData *instance = debugmalloc_singleton();
     bool ok = true;
     for (size_t i = 0; i < debugmalloc_tablesize; i++) {
         if (instance->head[i].next != &instance->tail[i]) {
             ok = false;
             break;
         }
     }
     if (!ok) {
         debugmalloc_log("********************************************************\n"
                         "* MEMORIASZIVARGAS VAN A PROGRAMBAN!!!\n"
                         "********************************************************\n");
         debugmalloc_dump();
     }
 }
References debugmalloc_dump(), debugmalloc_log(), debugmalloc_singleton(), debugmalloc_tablesize, DebugmallocData::head, DebugmallocElem::next, and DebugmallocData::tail.
Referenced by debugmalloc_create().
debugmalloc_canary_ok()
static bool debugmalloc_canary_ok (DebugmallocElem const * elem) static
Definition at line 171 of file debugmalloc.h.
{
     unsigned char *real_mem = (unsigned char *) elem->real_mem;
     unsigned char *canary1 = real_mem;
     unsigned char *canary2 = real_mem + debugmalloc_canary_size + elem->size;
     for (size_t i = 0; i < debugmalloc_canary_size; ++i) {
         if (canary1[i] != debugmalloc_canary_char)
             return false;
         if (canary2[i] != debugmalloc_canary_char)
             return false;
     }
     return true;
 }
References debugmalloc_canary_char, debugmalloc_canary_size, DebugmallocElem::real_mem, and DebugmallocElem::size.
Referenced by debugmalloc_dump_elem(), and debugmalloc_free_full().
debugmalloc_create()
static DebugmallocData * debugmalloc_create (void) static
Definition at line 430 of file debugmalloc.h.
{
     /* config check */
     if (debugmalloc_canary_size % 16 != 0) {
         debugmalloc_log("debugmalloc: a kanari merete legyen 16-tal oszthato\n");
         abort();
     }
     if (debugmalloc_canary_char == 0) {
         debugmalloc_log("debugmalloc: a kanari legyen 0-tol kulonbozo\n");
         abort();
     }
     /* avoid compiler warning if these functions are not used */
     (void) debugmalloc_realloc_full;
     (void) debugmalloc_log_file;
     (void) debugmalloc_allocated_count;
     /* create and initialize instance */
     DebugmallocData *instance = (DebugmallocData *) malloc(sizeof(DebugmallocData));
     if (instance == NULL) {
         debugmalloc_log("debugmalloc: nem sikerult elinditani a memoriakezelest\n");
         abort();
     }
     memset(instance, 0, sizeof(DebugmallocData));
     for (size_t i = 0; i < debugmalloc_tablesize; i++) {
         instance->head[i].prev = NULL;
         instance->head[i].next = &instance->tail[i];
         instance->tail[i].next = NULL;
         instance->tail[i].prev = &instance->head[i];
     }
     atexit(debugmalloc_atexit_dump);
     return instance;
 }
References debugmalloc_allocated_count(), debugmalloc_atexit_dump(), debugmalloc_canary_char, debugmalloc_canary_size, debugmalloc_log(), debugmalloc_log_file(), debugmalloc_realloc_full(), debugmalloc_tablesize, DebugmallocData::head, malloc, DebugmallocElem::next, DebugmallocElem::prev, and DebugmallocData::tail.
Referenced by debugmalloc_singleton().
debugmalloc_dump()
static void debugmalloc_dump (void) static
Definition at line 237 of file debugmalloc.h.
{
     DebugmallocData *instance = debugmalloc_singleton();
     debugmalloc_log("** DEBUGMALLOC DUMP ************************************\n");
     for (size_t i = 0; i < debugmalloc_tablesize; i++) {
         DebugmallocElem *head = &instance->head[i];
         for (DebugmallocElem *iter = head->next; iter->next != NULL; iter = iter->next)
             debugmalloc_dump_elem(iter);
     }
     debugmalloc_log("** DEBUGMALLOC DUMP VEGE *******************************\n");
 }
References debugmalloc_dump_elem(), debugmalloc_log(), debugmalloc_singleton(), debugmalloc_tablesize, DebugmallocData::head, and DebugmallocElem::next.
Referenced by debugmalloc_atexit_dump().
debugmalloc_dump_elem()
static void debugmalloc_dump_elem (DebugmallocElem const * elem) static
Definition at line 212 of file debugmalloc.h.
{
     bool canary_ok = debugmalloc_canary_ok(elem);
     debugmalloc_log("  MEMORIATERULET: %p, %u bajt, kanari: %s\n"
                     "    foglalas: %s:%u, %s(%s)\n",
                        elem->user_mem, (unsigned) elem->size, canary_ok ? "ok" : "**SERULT**",
                        elem->file, elem->line,
                        elem->func, elem->expr);
     if (!canary_ok) {
         debugmalloc_log("    ELOTTE kanari: \n");
         debugmalloc_dump_memory((char const *) elem->real_mem, debugmalloc_canary_size);
     }
     debugmalloc_log("    memoria eleje: \n");
     debugmalloc_dump_memory((char const *) elem->user_mem, elem->size > 64 ? 64 : elem->size);
     if (!canary_ok) {
         debugmalloc_log("    UTANA kanari: \n");
         debugmalloc_dump_memory((char const *) elem->real_mem + debugmalloc_canary_size + elem->size, debugmalloc_canary_size);
     }
 }
References debugmalloc_canary_ok(), debugmalloc_canary_size, debugmalloc_dump_memory(), debugmalloc_log(), DebugmallocElem::expr, DebugmallocElem::file, DebugmallocElem::func, DebugmallocElem::line, DebugmallocElem::real_mem, DebugmallocElem::size, and DebugmallocElem::user_mem.
Referenced by debugmalloc_dump(), and debugmalloc_free_full().
debugmalloc_dump_memory()
static void debugmalloc_dump_memory (char const * mem, size_t size) static
Definition at line 185 of file debugmalloc.h.
{
     for (unsigned y = 0; y < (size + 15) / 16; y++) {
         char line[80];
         int pos = 0;
         pos += sprintf(line + pos, "      %04x  ", y * 16);
         for (unsigned x = 0; x < 16; x++) {
             if (y * 16 + x < size)
                 pos += sprintf(line + pos, "%02x ", mem[y * 16 + x]);
             else
                 pos += sprintf(line + pos, "   ");
         }
         pos += sprintf(line + pos, "  ");
         for (unsigned x = 0; x < 16; x++) {
             if (y * 16 + x < size) {
                 unsigned char c = mem[y * 16 + x];
                 pos += sprintf(line + pos, "%c", isprint(c) ? c : '.');
             }
             else {
                 pos += sprintf(line + pos, " ");
             }
         }
         debugmalloc_log("%s\n", line);
     }
 }
References debugmalloc_log().
Referenced by debugmalloc_dump_elem().
debugmalloc_find()
static DebugmallocElem* debugmalloc_find (void * mem) static
Definition at line 293 of file debugmalloc.h.
{
     DebugmallocData *instance = debugmalloc_singleton();
     size_t idx = debugmalloc_hash(mem);
     DebugmallocElem *head = &instance->head[idx];
     for (DebugmallocElem *iter = head->next; iter->next != NULL; iter = iter->next)
         if (iter->user_mem == mem)
             return iter;
     return NULL;
 }
References debugmalloc_hash(), debugmalloc_singleton(), DebugmallocData::head, and DebugmallocElem::next.
Referenced by debugmalloc_free_full(), and debugmalloc_realloc_full().
debugmalloc_free_full()
static void debugmalloc_free_full (void * mem, char const * func, char const * file, unsigned line) static
Definition at line 373 of file debugmalloc.h.
{
     /* imitate standard free function: if ptr is null, no operation is performed */
     if (mem == NULL)
         return;
     /* find allocation, abort if not found */
     DebugmallocElem *deleted = debugmalloc_find(mem);
     if (deleted == NULL) {
         debugmalloc_log("debugmalloc: %s @ %s:%u: olyan teruletet akarsz felszabaditani, ami nincs lefoglalva!\n", func, file, line);
         abort();
     }
     /* check canary and then free memory */
     if (!debugmalloc_canary_ok(deleted)) {
         debugmalloc_log("debugmalloc: %s @ %s:%u: a %p memoriateruletet tulindexelted!\n", func, file, line, mem);
         debugmalloc_dump_elem(deleted);
     }
     debugmalloc_free_inner(deleted);
 }
References debugmalloc_canary_ok(), debugmalloc_dump_elem(), debugmalloc_find(), debugmalloc_free_inner(), and debugmalloc_log().
Referenced by debugmalloc_realloc_full().
debugmalloc_free_inner()
static void debugmalloc_free_inner (DebugmallocElem * deleted) static
Definition at line 358 of file debugmalloc.h.
{
     /* fill with garbage */
     memset(deleted->real_mem, debugmalloc_canary_char, deleted->size + 2 * debugmalloc_canary_size);
     /* free memory and remove from linked list */
     free(deleted->real_mem);
     deleted->next->prev = deleted->prev;
     deleted->prev->next = deleted->next;
     free(deleted);
 }
References debugmalloc_canary_char, debugmalloc_canary_size, free, DebugmallocElem::next, DebugmallocElem::prev, DebugmallocElem::real_mem, and DebugmallocElem::size.
Referenced by debugmalloc_free_full(), and debugmalloc_realloc_full().
debugmalloc_hash()
static size_t debugmalloc_hash (void * address) static
Definition at line 271 of file debugmalloc.h.
{
     /* the last few bits are ignored, as they are usually zero, because of
      * alignment purposes. all tested architectures used 16 byte allocation. */
     size_t cut = (size_t)address >> 4;
     return cut % debugmalloc_tablesize;
 }
References debugmalloc_tablesize.
Referenced by debugmalloc_find(), and debugmalloc_insert().
debugmalloc_insert()
static void debugmalloc_insert (DebugmallocElem * entry) static
Definition at line 280 of file debugmalloc.h.
{
     DebugmallocData *instance = debugmalloc_singleton();
     size_t idx = debugmalloc_hash(entry->user_mem);
     DebugmallocElem *head = &instance->head[idx];
     entry->prev = head;
     entry->next = head->next;
     head->next->prev = entry;
     head->next = entry;
 }
References debugmalloc_hash(), debugmalloc_singleton(), DebugmallocData::head, DebugmallocElem::next, DebugmallocElem::prev, and DebugmallocElem::user_mem.
Referenced by debugmalloc_malloc_full().
debugmalloc_log()
static void debugmalloc_log (char const * format, ...) static
Definition at line 134 of file debugmalloc.h.
{
     DebugmallocData *instance = debugmalloc_singleton();
     FILE *f = stderr;
     if (strcmp(instance->logfile, "") != 0) {
         f = fopen(instance->logfile, "at");
         if (f == NULL) {
             f = stderr;
             fprintf(stderr, "debugmalloc: nem tudom megnyitni a %s fajlt irasra!\n", instance->logfile);
             strcpy(instance->logfile, "");
         }
     }
     va_list ap;
     va_start(ap, format);
     vfprintf(f, format, ap);
     va_end(ap);
     if (f != stderr)
         fclose(f);
 }
References debugmalloc_singleton(), and DebugmallocData::logfile.
Referenced by debugmalloc_atexit_dump(), debugmalloc_create(), debugmalloc_dump(), debugmalloc_dump_elem(), debugmalloc_dump_memory(), debugmalloc_free_full(), debugmalloc_malloc_full(), and debugmalloc_realloc_full().
debugmalloc_log_file()
static void debugmalloc_log_file (char const * logfilename) static
Definition at line 124 of file debugmalloc.h.
{
     if (logfilename == NULL)
         logfilename = "";
     DebugmallocData *instance = debugmalloc_singleton();
     debugmalloc_strlcpy(instance->logfile, logfilename, sizeof(instance->logfile));
 }
References debugmalloc_singleton(), debugmalloc_strlcpy(), and DebugmallocData::logfile.
Referenced by debugmalloc_create().
debugmalloc_malloc_full()
static void* debugmalloc_malloc_full (size_t size, char const * func, char const * expr, char const * file, unsigned line, bool zero) static
Definition at line 317 of file debugmalloc.h.
{
     /* imitate standard malloc: return null if size is zero */
     if (size == 0)
         return NULL;
     /* allocate more memory, make room for canary */
     void *real_mem = malloc(size + 2 * debugmalloc_canary_size);
     if (real_mem == NULL) {
         debugmalloc_log("debugmalloc: %s @ %s:%u: nem sikerult %u meretu memoriat foglalni!\n", func, file, line, (unsigned) size);
         return NULL;
     }
     /* allocate memory for linked list element */
     DebugmallocElem *newentry = (DebugmallocElem *) malloc(sizeof(DebugmallocElem));
     if (newentry == NULL) {
         free(real_mem);
         debugmalloc_log("debugmalloc: %s @ %s:%u: le tudtam foglalni %u memoriat, de utana a sajatnak nem, sry\n", func, file, line, (unsigned) size);
         abort();
     }
     /* metadata of allocation: caller function, code line etc. */
     debugmalloc_strlcpy(newentry->func, func, sizeof(newentry->func));
     debugmalloc_strlcpy(newentry->expr, expr, sizeof(newentry->expr));
     debugmalloc_strlcpy(newentry->file, file, sizeof(newentry->file));
     newentry->line = line;
     /* address of allocated memory chunk */
     newentry->real_mem = real_mem;
     newentry->user_mem = (unsigned char *) real_mem + debugmalloc_canary_size;
     newentry->size = size;
     debugmalloc_memory_init(newentry, zero);
     /* store in list and return pointer to user area */
     debugmalloc_insert(newentry);
     return newentry->user_mem;
 }
References debugmalloc_canary_size, debugmalloc_insert(), debugmalloc_log(), debugmalloc_memory_init(), debugmalloc_strlcpy(), DebugmallocElem::expr, DebugmallocElem::file, free, DebugmallocElem::func, DebugmallocElem::line, malloc, DebugmallocElem::real_mem, DebugmallocElem::size, and DebugmallocElem::user_mem.
Referenced by debugmalloc_realloc_full().
debugmalloc_memory_init()
static void debugmalloc_memory_init (DebugmallocElem * elem, bool zero) static
Definition at line 160 of file debugmalloc.h.
{
     unsigned char *real_mem = (unsigned char *) elem->real_mem;
     unsigned char *user_mem = (unsigned char *) elem->user_mem;
     unsigned char *canary1 = real_mem;
     unsigned char *canary2 = real_mem + debugmalloc_canary_size + elem->size;
     memset(canary1, debugmalloc_canary_char, debugmalloc_canary_size);
     memset(canary2, debugmalloc_canary_char, debugmalloc_canary_size);
     memset(user_mem, zero ? 0 : debugmalloc_canary_char, elem->size);
 }
References debugmalloc_canary_char, debugmalloc_canary_size, DebugmallocElem::real_mem, DebugmallocElem::size, and DebugmallocElem::user_mem.
Referenced by debugmalloc_malloc_full().
debugmalloc_realloc_full()
static void* debugmalloc_realloc_full (void * oldmem, size_t newsize, char const * func, char const * expr, char const * file, unsigned line) static
Definition at line 395 of file debugmalloc.h.
{
     /* imitate standard realloc: equivalent to malloc if first param is NULL */
     if (oldmem == NULL)
         return debugmalloc_malloc_full(newsize, func, expr, file, line, 0);
     /* imitate standard realloc: equivalent to free if size is null. */
     if (newsize == 0) {
         debugmalloc_free_full(oldmem, func, file, line);
         return NULL;
     }
     /* find old allocation. abort if not found. */
     DebugmallocElem *entry = debugmalloc_find(oldmem);
     if (entry == NULL) {
         debugmalloc_log("debugmalloc: %s @ %s:%u: olyan teruletet akarsz atmeretezni, ami nincs lefoglalva!\n", func, file, line);
         abort();
     }
     /* create new allocation */
     void *newmem = debugmalloc_malloc_full(newsize, func, expr, file, line, false);
     if (newmem == NULL) {
         debugmalloc_log("debugmalloc: %s @ %s:%u: nem sikerult uj memoriat foglalni az atmeretezeshez!\n", func, file, line);
         /* imitate standard realloc: original block is untouched, but return NULL */
         return NULL;
     }
     /* copy old data */
     size_t smaller = entry->size < newsize ? entry->size : newsize;
     memcpy(newmem, oldmem, smaller);
     debugmalloc_free_inner(entry);
     return newmem;
 }
References debugmalloc_find(), debugmalloc_free_full(), debugmalloc_free_inner(), debugmalloc_log(), debugmalloc_malloc_full(), and DebugmallocElem::size.
Referenced by debugmalloc_create().
debugmalloc_singleton()
static DebugmallocData* debugmalloc_singleton (void) static
Definition at line 82 of file debugmalloc.h.
{
     static char envstr[100];
     static void *instance = NULL;
     /* if we do not know the address of the singleton:
      * - maybe we are the one to create it (env variable also does not exist)
      * - or it is already created, and stored in the env variable. */
     if (instance == NULL) {
         char envvarname[100] = "";
         sprintf(envvarname, "%s%d", "debugmallocsingleton", (int) getpid());
         char *envptr = getenv(envvarname);
         if (envptr == NULL) {
             /* no env variable: create singleton. */
             instance = debugmalloc_create();
             sprintf(envstr, "%s=%p", envvarname, instance);
             putenv(envstr);
         } else {
             /* another copy of this function already created it. */
             int ok = sscanf(envptr, "%p", &instance);
             if (ok != 1) {
                 fprintf(stderr, "debugmalloc: nem lehet ertelmezni: %s!\n", envptr);
                 abort();
             }
         }
     }
     return (DebugmallocData *) instance;
 }
References debugmalloc_create().
Referenced by debugmalloc_allocated_count(), debugmalloc_atexit_dump(), debugmalloc_dump(), debugmalloc_find(), debugmalloc_insert(), debugmalloc_log(), and debugmalloc_log_file().
debugmalloc_strlcpy()
static void debugmalloc_strlcpy (char * dest, char const * src, size_t destsize) static
Definition at line 115 of file debugmalloc.h.
{
     strncpy(dest, src, destsize);
     dest[destsize - 1] = '\0';
 }
Referenced by debugmalloc_log_file(), and debugmalloc_malloc_full().