s502 assembler: src/istack.c File Reference
istack.c File Reference
implement istack member functions
#include "debugmalloc.h"
#include <stdlib.h>
#include "istack.h"
#include "logging.h"
Functions
istack_ptr istack_new ()
int istack_empty (istack_ptr istack)
int istack_push (istack_ptr istack, int val)
int istack_pop (istack_ptr istack)
int istack_top (istack_ptr istack, int def)
void istack_free (istack_ptr istack)
Detailed Description
implement istack member functions
See istack.h if doxygen again refuses to show doc comments from there!
Definition in file istack.c.
Function Documentation
istack_empty()
int istack_empty (istack_ptr istack)
Definition at line 26 of file istack.c.
{
     return (!istack->next);
 };
References istack_el::next.
istack_free()
void istack_free (istack_ptr istack)
Definition at line 59 of file istack.c.
{
     while (!istack_empty(istack)) istack_pop(istack);
     free(istack);
 }
References istack_el::istack_empty(), and istack_el::istack_pop().
istack_new()
istack_ptr istack_new ()
Definition at line 15 of file istack.c.
{
     istack_ptr head = malloc(sizeof(istack_el));
     if (!head) {
         ERROR("Memory allocation error in istack_new()!\n");
         return NULL;
     }
     head->next = NULL;
     return head;
 }
References ERROR, and istack_el::next.
istack_pop()
int istack_pop (istack_ptr istack)
Definition at line 44 of file istack.c.
{
     if (istack_empty(istack)) return -1;
     istack_ptr elem = istack->next;
     istack->next = elem->next;
     free(elem);
     return 0;
 }
References istack_el::istack_empty(), and istack_el::next.
istack_push()
int istack_push (istack_ptr istack, int val)
Definition at line 31 of file istack.c.
{
     istack_ptr elem = malloc(sizeof(istack_el));
     if (!elem) {
         ERROR("Memory allocation error in istack_push()!\n");
         return -1;
     }
     elem->val = val;
     elem->next = istack->next;
     istack->next = elem;
     return 0;
 }
References ERROR, istack_el::next, and istack_el::val.
istack_top()
int istack_top (istack_ptr istack, int def)
Definition at line 53 of file istack.c.
{
     if (istack_empty(istack)) return def;
     return istack->next->val;
 };
References istack_el::istack_empty(), and istack_el::next.