s502 assembler: src/loadfile.h File Reference
loadfile.h File Reference
File reading step.
#include "tokenslist.h"
Functions
TokensList * load_file (char *name)
load and parse one file
Detailed Description
File reading step.
Definition in file loadfile.h.
Function Documentation
load_file()
TokensList* load_file (char * name)
load and parse one file
Load file, parse into tokens, build TokensList, identify token types
Parameters
name file name / path to load
Returns
list of tokens in file or NULL on error
Definition at line 166 of file loadfile.c.
{
     LOG(3, "Reading file...\n");
     TokensList* list = read_file(name);
     if (list == NULL)
         goto ERROR;
     LOG(3, "Running first analysis...\n");
     if (tokenslist_recognize(list) < 0)
         goto ERROR;
     return list;
 ERROR:
     FAIL("Failed to load file contents: '%s'\n", name);
     tokenslist_free(list);
     return NULL;
 }
References ERROR, FAIL, LOG, read_file(), TokensList::tokenslist_free(), and TokensList::tokenslist_recognize().
Referenced by main().