s502 assembler: src/number.c File Reference
number.c File Reference
implement number module functions
#include <string.h>
#include "number.h"
#include "logging.h"
Functions
int number_char_to_digit (char c)
Convert a hex char to a digit.
int number_parse_number (char *str)
interpret a string as a decimal or hex number
int number_get_raw (State *s, char *str)
interpret number without modifiers
int number_get_number (State *s, char *str)
interpret a string as a constant, label or number
Detailed Description
implement number module functions
Definition in file number.c.
Function Documentation
number_char_to_digit()
int number_char_to_digit (char c)
Convert a hex char to a digit.
Parameters
c char to convert
Returns
value or NUMBER_ERROR on some error
Handles upper or lowercase chars
Returns NUMBER_ERROR on failed conversion
Definition at line 12 of file number.c.
{
     if ('0' <= c && c <= '9')
         return c - '0';
     if ('a' <= c && c <= 'f')
         c += 'A' - 'a';
     if ('A' <= c && c <= 'F')
         return c - 'A' + 10;
     return NUMBER_ERROR;
 }
References NUMBER_ERROR.
Referenced by instruction_load(), and number_parse_number().
number_get_number()
int number_get_number (State * s, char * str)
interpret a string as a constant, label or number
Parameters
s State to read constant / label values from
str string to interpret
get the value of a constant or label
parse number
handles modifier symbols
Returns NUMBER_ERROR on error, or NUMBER_LABEL_NODEF if number is a valid label with no value
Definition at line 75 of file number.c.
{
     int p = (str[0] == '>' || str[0] == '<') ? 1 : 0;
     int num = number_get_raw(s, &str[p]);
     if (num < 0) return num;
     num = str[0] == '>' ? num >> 8 : num;
     num &= str[0] == '>' || str[0] == '<' ? 0xff : 0xffff;
     return num;
 }
References number_get_raw().
Referenced by compile_data(), compile_pad(), and token_get_operand().
number_get_raw()
int number_get_raw (State * s, char * str)
interpret number without modifiers
Parameters
s state to read from
str string to interpret
Resolves labels & constants, parses numbers
Does not interpret modifiers
Definition at line 62 of file number.c.
{
     if (str[0] == '@' || str[0] == '&') {
         Map* m = str[0] == '@' ? s->defines : s->labels;
         int n = map_get(m, &str[1]);
         if (n < 0) {
             return str[0] == '@' ? NUMBER_ERROR : NUMBER_LABEL_NODEF;
         }
         return n;
     }
     // pass error (NUMBER_ERROR value)
     return number_parse_number(str);
 }
References State::defines, State::labels, Map::map_get(), NUMBER_ERROR, NUMBER_LABEL_NODEF, and number_parse_number().
Referenced by number_get_number().
number_parse_number()
int number_parse_number (char * str)
interpret a string as a decimal or hex number
Parameters
str string to interpret
Returns
string as a number or NUMBER_ERROR
This one only parses decimals and hexes without any modifiers
Definition at line 30 of file number.c.
{
     int count = strlen(str);
     int base = 10;
     int ptr = 0;
     int num = 0;
     if (str[0] == '$') {
         base = 16;
         ptr++;
     }
     while (ptr < count) {
         num *= base;
         int digit = number_char_to_digit(str[ptr]);
         if (digit == NUMBER_ERROR || digit >= base) {
             ERROR("Can not interpret number: '%.*s'\n", count, str);
             return NUMBER_ERROR;
         }
         num += digit;
         ptr++;
     }
     return num;
 }
References ERROR, number_char_to_digit(), and NUMBER_ERROR.
Referenced by number_get_raw().