s502 assembler: src/number.h File Reference
number.h File Reference
Number module to parse numbers.
#include "state.h"
Enumerations
enum {
OPC_INVALID = 0xff, MAP_MAX_KEY_LEN = 32, NUMBER_ERROR = -1, NUMBER_LABEL_NODEF = -2,
STATE_MAX_STRING_LEN = 32, TOKEN_BUFFER_SIZE = 100, TOKEN_SOURCE_FILE_SIZE = 32
}
Functions
int number_get_number (State *s, char *str)
interpret a string as a constant, label or number
int number_char_to_digit (char c)
Convert a hex char to a digit.
Detailed Description
Number module to parse numbers.
Handles number in decimal and hex, labels, constants and modifiers
Definition in file number.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OPC_INVALID
An invalid opcode to signal invalid / non-existent variations.
MAP_MAX_KEY_LEN
Key buffer size for Map.
NUMBER_ERROR
Could not parse a number or constant is undefined.
NUMBER_LABEL_NODEF
Undefined label.
STATE_MAX_STRING_LEN
max string length for input/output files
TOKEN_BUFFER_SIZE
Token max length.
TOKEN_SOURCE_FILE_SIZE
source filename max length. Longer strings will get truncated.
Definition at line 13 of file number.h.
      {
     NUMBER_ERROR = -1,
     NUMBER_LABEL_NODEF = -2,
 };
Function Documentation
number_char_to_digit()
int number_char_to_digit (char c)
Convert a hex char to a digit.
Parameters
c char to convert
Returns
value or NUMBER_ERROR on some error
Handles upper or lowercase chars
Returns NUMBER_ERROR on failed conversion
Definition at line 12 of file number.c.
{
     if ('0' <= c && c <= '9')
         return c - '0';
     if ('a' <= c && c <= 'f')
         c += 'A' - 'a';
     if ('A' <= c && c <= 'F')
         return c - 'A' + 10;
     return NUMBER_ERROR;
 }
References NUMBER_ERROR.
Referenced by instruction_load(), and number_parse_number().
number_get_number()
int number_get_number (State * s, char * str)
interpret a string as a constant, label or number
Parameters
s State to read constant / label values from
str string to interpret
get the value of a constant or label
parse number
handles modifier symbols
Returns NUMBER_ERROR on error, or NUMBER_LABEL_NODEF if number is a valid label with no value
Definition at line 75 of file number.c.
{
     int p = (str[0] == '>' || str[0] == '<') ? 1 : 0;
     int num = number_get_raw(s, &str[p]);
     if (num < 0) return num;
     num = str[0] == '>' ? num >> 8 : num;
     num &= str[0] == '>' || str[0] == '<' ? 0xff : 0xffff;
     return num;
 }
References number_get_raw().
Referenced by compile_data(), compile_pad(), and token_get_operand().