s502 assembler: src/pass_twothree.h File Reference
pass_twothree.h File Reference
processing steps 2 and 3
#include "state.h"
Functions
int pass_two (State *s)
compilation pass 2
int write_data (State *s)
compilation pass 3
Detailed Description
processing steps 2 and 3
Check out documentation on steps
Definition in file pass_twothree.h.
Function Documentation
pass_two()
int pass_two (State * s)
compilation pass 2
Parameters
s current state
Returns
0 on success, -1 on error
Simply subtitutes remaining operand values (forward labels).
Definition at line 19 of file pass_twothree.c.
{
     for (TokensListElement* ptr = s->tokens->head; ptr != NULL; ptr = ptr->next) {
         int ret = token_get_operand(s, ptr->token);
         if (ret < 0 || (ptr->token->type == TT_INSTR && (ptr->token->instr.number < 0))) {
             if (ret == 0) {
                 ERROR("Undefined label reference!\n");
             }
             token_print(ptr->token);
             FAIL("Pass two failed!\n");
             return -1;
         }
     }
     return 0;
 }
References ERROR, FAIL, TokensList::head, TokensListElement::next, Token::token_get_operand(), Token::token_print(), State::tokens, and TT_INSTR.
Referenced by main().
write_data()
int write_data (State * s)
compilation pass 3
Parameters
s current state
Returns
0 on success, -1 on error
Writes binary data to file
Definition at line 69 of file pass_twothree.c.
{
     // first concat, then write
     // this way we only write (and destroy possible prev. file) if we can do that
     int l;
     char* data = concat_bin(s, &l);
     if (!data) {
         FAIL("Could not compile data!\n");
         return -1;
     }
     FILE* f = fopen(s->outfile, "wb");
     if (!f) {
         ERROR("An error occured opening the file %s!\n", s->outfile);
         ERROR("Error opening file: %s\n", strerror(errno));
         free(data);
         return -1;
     }
     fwrite(data, 1, l, f);
     free(data);
     fclose(f);
     return 0;
 }
References concat_bin(), ERROR, FAIL, and State::outfile.
Referenced by main().