s502 assembler: TokensList Class Reference
TokensList Class Reference
A doubly-linked list for storing Tokens.
#include <tokenslist.h>
Public Member Functions
TokensList * tokenslist_new ()
Create a new (empty) TokensList object.
int tokenslist_add (TokensList *list, Token t)
Append a token to the list.
TokensListElement * tokenslist_remove (TokensList *list, TokensListElement *el)
remove a token from the list
void tokenslist_insert (TokensList *list, TokensListElement *target, TokensList *src)
Insert the contents of SRC into another list after an element.
void tokenslist_free (TokensList *list)
free ALL memory associated with the TokensList object
void tokenslist_debug_print (TokensList *list)
Pretty-print all tokens in a list.
int tokenslist_recognize (TokensList *t)
Do token recognition on all tokens in a list.
Data Fields
TokensListElement * head
head (first element) of the list
TokensListElement * tail
tail (last element) pointer
Detailed Description
A doubly-linked list for storing Tokens.
Definition at line 29 of file tokenslist.h.
Member Function Documentation
tokenslist_add()
int tokenslist_add (TokensList * list, Token t)
Append a token to the list.
Returns
0 on success or -1 on error
Definition at line 31 of file tokenslist.c.
{
     TokensListElement* elem = (TokensListElement*)malloc(sizeof(TokensListElement));
     if (elem == NULL) goto ERR_MEM;
     elem->next = NULL;
     elem->prev = NULL;
     elem->token = malloc(sizeof(Token));
     if (!elem->token) goto ERR_MEM;
     *elem->token = t;
     if (list->head == NULL) {
         list->head = elem;
         list->tail = elem;
         return 0;
     }
     list->tail->next = elem;
     elem->prev = list->tail;
     list->tail = elem;
     return 0;
 ERR_MEM:
     if (elem) {
         if (elem->token)
             free(elem->token);
         free(elem);
     }
     ERROR("Memory allocation error in tokenslist_add()!\n");
     return -1;
 }
Referenced by read_file().
tokenslist_debug_print()
void tokenslist_debug_print (TokensList * list)
Pretty-print all tokens in a list.
Intended for debugging
Definition at line 89 of file tokenslist.c.
{
     LOG(0, "Dumping code:\n");
     for (TokensListElement* ptr = list->head; ptr != NULL; ptr = ptr->next)
         token_print(ptr->token);
 }
Referenced by main().
tokenslist_free()
void tokenslist_free (TokensList * list)
free ALL memory associated with the TokensList object
Pointer should be NULLed after this!
Definition at line 78 of file tokenslist.c.
{
     if (!list) return;
     while (list->head != NULL) {
         tokenslist_remove(list, list->head);
     }
     free(list);
 }
Referenced by load_file(), read_file(), and state_free().
tokenslist_insert()
void tokenslist_insert (TokensList * list, TokensListElement * target, TokensList * src)
Insert the contents of SRC into another list after an element.
Keeps the original element in place
Definition at line 97 of file tokenslist.c.
{
     TokensListElement* next = pos->next;
     if (src->head == NULL)
         return;
     // doubly-link starts
     pos->next = src->head;
     src->head->prev = pos;
     src->tail->next = next;
     if (next != NULL)
         next->prev = src->tail;
     src->head = NULL;
     src->tail = NULL;
 }
tokenslist_new()
TokensList * tokenslist_new ()
Create a new (empty) TokensList object.
Returns
the new TokensList* or NULL on error
Definition at line 17 of file tokenslist.c.
{
     TokensList* ret = (TokensList*)malloc(sizeof(TokensList));
     if (ret == NULL) {
         ERROR("Memory allocation error in tokenslist_new()!\n");
         return NULL;
     }
     ret->head = NULL;
     ret->tail = NULL;
     return ret;
 }
Referenced by read_file().
tokenslist_recognize()
int tokenslist_recognize (TokensList * t)
Do token recognition on all tokens in a list.
Parameters
t tokenslist to use
Returns
0 on success, -1 on error
Definition at line 117 of file tokenslist.c.
{
     for (TokensListElement* ptr = t->head; ptr != NULL; ptr = ptr->next)
         if (token_recognize(ptr->token) < 0) {
             FAIL("Can not recognize token types!\n");
             return -1;
         }
     return 0;
 }
Referenced by load_file().
tokenslist_remove()
TokensListElement * tokenslist_remove (TokensList * list, TokensListElement * el)
remove a token from the list
Returns
the next element of the list (can be NULL)
The reason why we return is that we use it in an iteration over the same list
Definition at line 60 of file tokenslist.c.
{
     if (list->head == el)
         list->head = el->next;
     if (list->tail == el)
         list->tail = el->prev;
     if (el->next != NULL)
         el->next->prev = el->prev;
     if (el->prev != NULL) {
         el->prev->next = el->next;
     }
     TokensListElement* next = el->next;
     free(el->token);
     free(el);
     return next;
 }
Referenced by pass_one(), and tokenslist_free().
Field Documentation
head
TokensListElement* TokensList::head
head (first element) of the list
Definition at line 31 of file tokenslist.h.
Referenced by concat_bin(), pass_one(), pass_two(), tokenslist_add(), tokenslist_debug_print(), tokenslist_free(), tokenslist_insert(), tokenslist_new(), tokenslist_recognize(), and tokenslist_remove().
tail
TokensListElement* TokensList::tail
tail (last element) pointer
Definition at line 33 of file tokenslist.h.
Referenced by tokenslist_add(), tokenslist_insert(), tokenslist_new(), and tokenslist_remove().
The documentation for this class was generated from the following file:
src/tokenslist.h