s502 assembler: Map Class Reference
Map Class Reference
Simple key->value map (str->int)
#include <map.h>
Public Member Functions
Map * map_new ()
Create a new map with 0 elements.
int map_set (Map *map, char *name, int value)
Sets a key in the map.
int map_get (Map *map, char *name)
Get the value of a key.
void map_free (Map *map)
Free the map with all associated memory.
void map_debug_print (Map *map)
Print all key-value pairs of the map.
Data Fields
struct MapEntry * head
Private Member Functions
struct MapEntry * map_find (Map *map, char *key)
Find a key in a map.
Detailed Description
Simple key->value map (str->int)
Implemented with a linked list.
Should only store non-negative values, as "NOT FOUND" value is -1
Definition at line 34 of file map.h.
Member Function Documentation
map_debug_print()
void map_debug_print (Map * map)
Print all key-value pairs of the map.
Parameters
map the map to print
Intended for debugging purposes
Definition at line 85 of file map.c.
{
     for (struct MapEntry* ptr = map->head; ptr != NULL; ptr = ptr->next)
         printf("\t%s:\t\t%d\n", ptr->name, ptr->value);
 }
Referenced by main().
map_find()
struct MapEntry * map_find (Map * map, char * key) private
Find a key in a map.
Returns
NULL if not found
Parameters
map map to search in
key key to search for
Definition at line 35 of file map.c.
{
     for (struct MapEntry* ptr = map->head; ptr != NULL; ptr = ptr->next)
         if (strncmp(ptr->name, key, MAP_MAX_KEY_LEN) == 0)
             return ptr;
     return NULL;
 }
References head, MAP_MAX_KEY_LEN, and MapEntry::next.
Referenced by map_get(), and map_set().
map_free()
void map_free (Map * map)
Free the map with all associated memory.
Parameters
map the map to free
Frees the map itself, so it's pointer will be invalid and should be NULLed!
Definition at line 62 of file map.c.
{
     if (!map) return;
     struct MapEntry* ptr;
     while (map->head != NULL) {
         ptr = map->head->next;
         free(map->head);
         map->head = ptr;
     }
     map->head = NULL;
     free(map);
 }
Referenced by state_free().
map_get()
int map_get (Map * map, char * name)
Get the value of a key.
Returns
the value of the key or -1 on not found
Parameters
map the map to search in
name key to search for
Definition at line 75 of file map.c.
{
     LOG(5, "Getting %s\n", name);
     struct MapEntry* p = map_find(map, name);
     if (p == NULL)
         return -1;
     return p->value;
 }
Referenced by number_get_raw(), and pass_one().
map_new()
Map * map_new ()
Create a new map with 0 elements.
Returns
the new map or NULL on error
Definition at line 17 of file map.c.
                {
     Map* ret = (Map*)malloc(sizeof(Map));
     if (ret == NULL) {
         ERROR("Memory allocation error in map_new()!\n");
         return NULL;
     }
     ret->head = NULL;
     return ret;
 }
Referenced by state_new().
map_set()
int map_set (Map * map, char * name, int value)
Sets a key in the map.
Parameters
map map to set key in
name key to set
value non-negative value to set for the key
Returns
0 on success, -1 on error
Definition at line 43 of file map.c.
{
     struct MapEntry* ptr = map_find(map, name);
     if (ptr == 0) {
         ptr = (struct MapEntry*)malloc(sizeof(struct MapEntry));
         if (ptr == NULL) {
             ERROR("Memory allocation error in map_set()!\n");
             return -1;
         }
         ptr->next = map->head;
         map->head = ptr;
         strncpy(ptr->name, name, MAP_MAX_KEY_LEN - 1);
         ptr->name[MAP_MAX_KEY_LEN - 1] = 0;
     }
     ptr->value = value;
     return 0;
 }
Referenced by pass_one(), and state_parse_commandline().
Field Documentation
head
struct MapEntry* Map::head
Definition at line 35 of file map.h.
Referenced by map_debug_print(), map_find(), map_free(), map_new(), and map_set().
The documentation for this class was generated from the following files:
src/map.h
src/map.c