s502 assembler: /github/workspace/src/tokenslist.c File Reference
tokenslist.c File Reference
implement TokensList methods
#include "debugmalloc.h"
#include <stdio.h>
#include <stdlib.h>
#include "tokenslist.h"
#include "tokenFunc.h"
#include "logging.h"
Macros
#define __USE_MINGW_ANSI_STDIO 1
Functions
TokensList * tokenslist_new ()
int tokenslist_add (TokensList *list, Token t)
TokensListElement * tokenslist_remove (TokensList *list, TokensListElement *el)
void tokenslist_free (TokensList *list)
void tokenslist_debug_print (TokensList *list)
void tokenslist_insert (TokensList *list, TokensListElement *pos, TokensList *src)
int tokenslist_recognize (TokensList *t)
Detailed Description
implement TokensList methods
See also
TokensList
Definition in file tokenslist.c.
Macro Definition Documentation
__USE_MINGW_ANSI_STDIO
#define __USE_MINGW_ANSI_STDIO 1
Definition at line 3 of file tokenslist.c.
Function Documentation
tokenslist_add()
int tokenslist_add (TokensList * list, Token t)
Definition at line 31 of file tokenslist.c.
{
     TokensListElement* elem = (TokensListElement*)malloc(sizeof(TokensListElement));
     if (elem == NULL) goto ERR_MEM;
     elem->next = NULL;
     elem->prev = NULL;
     elem->token = malloc(sizeof(Token));
     if (!elem->token) goto ERR_MEM;
     *elem->token = t;
     if (list->head == NULL) {
         list->head = elem;
         list->tail = elem;
         return 0;
     }
     list->tail->next = elem;
     elem->prev = list->tail;
     list->tail = elem;
     return 0;
 ERR_MEM:
     if (elem) {
         if (elem->token)
             free(elem->token);
         free(elem);
     }
     ERROR("Memory allocation error in tokenslist_add()!\n");
     return -1;
 }
References ERROR, free, TokensList::head, malloc, TokensListElement::next, TokensListElement::prev, TokensList::tail, and TokensListElement::token.
tokenslist_debug_print()
void tokenslist_debug_print (TokensList * list)
Definition at line 89 of file tokenslist.c.
{
     LOG(0, "Dumping code:\n");
     for (TokensListElement* ptr = list->head; ptr != NULL; ptr = ptr->next)
         token_print(ptr->token);
 }
References TokensList::head, LOG, TokensListElement::next, and Token::token_print().
tokenslist_free()
void tokenslist_free (TokensList * list)
Definition at line 78 of file tokenslist.c.
{
     if (!list) return;
     while (list->head != NULL) {
         tokenslist_remove(list, list->head);
     }
     free(list);
 }
References free, TokensList::head, and TokensList::tokenslist_remove().
tokenslist_insert()
void tokenslist_insert (TokensList * list, TokensListElement * pos, TokensList * src)
Definition at line 97 of file tokenslist.c.
{
     TokensListElement* next = pos->next;
     if (src->head == NULL)
         return;
     // doubly-link starts
     pos->next = src->head;
     src->head->prev = pos;
     src->tail->next = next;
     if (next != NULL)
         next->prev = src->tail;
     src->head = NULL;
     src->tail = NULL;
 }
References TokensList::head, TokensListElement::next, TokensListElement::prev, and TokensList::tail.
tokenslist_new()
TokensList* tokenslist_new ()
Definition at line 17 of file tokenslist.c.
{
     TokensList* ret = (TokensList*)malloc(sizeof(TokensList));
     if (ret == NULL) {
         ERROR("Memory allocation error in tokenslist_new()!\n");
         return NULL;
     }
     ret->head = NULL;
     ret->tail = NULL;
     return ret;
 }
References ERROR, TokensList::head, malloc, and TokensList::tail.
tokenslist_recognize()
int tokenslist_recognize (TokensList * t)
Definition at line 117 of file tokenslist.c.
{
     for (TokensListElement* ptr = t->head; ptr != NULL; ptr = ptr->next)
         if (token_recognize(ptr->token) < 0) {
             FAIL("Can not recognize token types!\n");
             return -1;
         }
     return 0;
 }
References FAIL, TokensList::head, TokensListElement::next, and Token::token_recognize().
tokenslist_remove()
TokensListElement* tokenslist_remove (TokensList * list, TokensListElement * el)
Definition at line 60 of file tokenslist.c.
{
     if (list->head == el)
         list->head = el->next;
     if (list->tail == el)
         list->tail = el->prev;
     if (el->next != NULL)
         el->next->prev = el->prev;
     if (el->prev != NULL) {
         el->prev->next = el->next;
     }
     TokensListElement* next = el->next;
     free(el->token);
     free(el);
     return next;
 }
References free, TokensList::head, TokensListElement::next, TokensListElement::prev, TokensList::tail, and TokensListElement::token.