s502 assembler: src/util.h File Reference
util.h File Reference
various utility functions
Functions
char * util_find_string_segment (char *ptr)
find pointer to next space or null in string
int util_match_char (char a, char b)
Case-insensitive character compare.
int util_match_string (char *first, char *second, int count)
case-insensitive memcmp
char ** util_split_string (char *str, int *n)
split a string into segments on spaces
Detailed Description
various utility functions
Definition in file util.h.
Function Documentation
util_find_string_segment()
char* util_find_string_segment (char * ptr)
find pointer to next space or null in string
Parameters
ptr string to search in
Returns
address of next space or null character in string
Definition at line 15 of file util.c.
{
     char* end = ptr;
     while (*end != ' ' && *end != '\0') end++;
     return end;
 }
util_match_char()
int util_match_char (char a, char b)
Case-insensitive character compare.
Parameters
a first char to compare
b second char to compare
Returns
0 if the two characters match, 1 otherwise
Definition at line 21 of file util.c.
{
     return a == b ||
         (
             (
                 (('a' <= a && a <= 'z') || ('A' <= a && a <= 'Z')) && // a is a letter
                 (('a' <= b && b <= 'z') || ('A' <= b && b <= 'Z'))    // b is a letter
                 ) &&
             (a - b == 'A' - 'a' || a - b == 'a' - 'A')
             );
 }
Referenced by Token::token_get_addressmode(), and util_match_string().
util_match_string()
int util_match_string (char * first, char * second, int count)
case-insensitive memcmp
Parameters
count how many bytes to match
first first string to compare
second second string to compare
Returns
0 if the strings match, 1 otherwise
Definition at line 32 of file util.c.
{
     for (int i = 0; i < count; i++) {
         if (!util_match_char(first[i], second[i])) return 1;
     }
     return 0;
 }
References util_match_char().
Referenced by directive_compile(), and instruction_find().
util_split_string()
char** util_split_string (char * str, int * n)
split a string into segments on spaces
Parameters
str string to split
n int pointer to return segment count to
Returns
an array of substrings
Uses a not-so-nice trick to enable easier handling
The returned *char[] also contains a buffer with the actual substring data
This also means simply freeing it is all what is needed to be done on the caller side
Definition at line 39 of file util.c.
{
     // function to split a string into substrings on spaces
     // uses an ugly trick to avoid multiple buffers
     // (we NEED to store a copy of the original data bc we must write 0 terminators)
     int l = strlen(str);
     // count segments
     int m = 1;
     for (int i = 0; i < l; i++)
         if (str[i] == ' ') m++;
     *n = m;
     // the buffers stores the *char[]-s and then the copy of the data
     char** r = malloc(sizeof(char*) * m + l + 1);
     char* buf = (char*)r + sizeof(char*) * m;
     strcpy(buf, str);
     // first segemtn is the begining of the string
     r[0] = buf;
     // fill the table and write 0 terminators
     int j = 1;
     for (int i = 0; i < l; i++)
         if (str[i] == ' ') {
             buf[i] = 0;
             r[j++] = buf + i + 1;
         }
     return r;
 }
Referenced by compile_data(), and compile_pad().